name: Format
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-format:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/ptsouchlos/modern-cv-dev:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Check formatting
        run: find . -iname "*.typ" | xargs typstyle --check
