name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/ptsouchlos/modern-cv-dev:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Uninstall previous local install
        run: just uninstall

      - name: Show test runner fonts
        run: tt util fonts --use-system-fonts

      - name: Run test suite
        run: just test

      - name: Archive diffs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: diffs-typst
          path: |
            tests/**/diff/*.png
            tests/**/out/*.png
            tests/**/ref/*.png
          retention-days: 5

      - name: Build docs
        run: just doc

      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: manual
          path: docs/manual.pdf
